spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://58.213.48.27:3306/GZGL?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: lyw123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
wechat:
  APPID: wxde9aeb9d7982fe19
  APPSECRET: 69c5542b32005b0e7d39f25510f653f5